import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

import java.util.Arrays;
import java.util.Collection;

import static org.junit.Assert.assertEquals;

@RunWith(Parameterized.class)
public class Day2Test {
    // X = lose, Y = draw (3), Z = win (6)

    @Parameterized.Parameters
    public static Collection<Object[]> data() {
        return Arrays.asList(new Object[][] {
                { "A X", 1 + 3, "Rock v Rock", 3, "Rock v Lose" },
                { "A Y", 2 + 6, "Rock v Paper", 4, "Rock v Draw" },
                { "A Z", 3 + 0, "Rock v Scissors", 8, "Rock v Win" },
                { "B X", 1 + 0, "Paper v Rock", 1, "Paper v Lose" },
                { "B Y", 2 + 3, "Paper v Paper", 5, "Paper v Draw" },
                { "B Z", 3 + 6, "Paper v Scissors", 9, "Paper v Win" },
                { "C X", 1 + 6, "Scissors v Rock", 2, "Scissors v Lose" },
                { "C Y", 2 + 0, "Scissors v Paper", 6, "Scissors v Draw" },
                { "C Z", 3 + 3, "Scissors v Scissors", 7, "Scissors v Win" },
                { "A Y\n" +
                  "B X\n" +
                  "C Z", 15, "Example Game", 12, "Example Game"},
                { REAL_PUZZLE, 8933, "Real Puzzle", 0, "Real Puzzle"}
        });
    }

    private final String games;
    private final int outcomeForThrowTranslation;
    private final String throwTranslationDescription;

    private final int outcomeForWinLoseDrawTranslation;
    private final String winLoseDrawDescription;

    public Day2Test(String games,
                    int outcomeForThrowTranslation, String throwTranslationDescription,
                    int outcomeForWinLoseDrawTranslation, String winLoseDrawDescription){
        this.games = games;
        this.outcomeForThrowTranslation = outcomeForThrowTranslation;
        this.throwTranslationDescription = throwTranslationDescription;
        this.outcomeForWinLoseDrawTranslation = outcomeForWinLoseDrawTranslation;
        this.winLoseDrawDescription = winLoseDrawDescription;

    }

    @Test
    public void shouldReturnCorrectOutcome_Part1(){
        assertEquals(throwTranslationDescription + " should have returned " + outcomeForThrowTranslation,
                outcomeForThrowTranslation,
                RockPaperScissors.shoot(games));
    }

    @Test
    public void shouldReturnCorrectOutcome_Part2(){
        assertEquals(winLoseDrawDescription + " should have returned " +
                outcomeForWinLoseDrawTranslation, outcomeForWinLoseDrawTranslation,
                RockPaperScissors.thinkAndShoot(games));
    }

    private static final String REAL_PUZZLE = "B X\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "A Y\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "A Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A X\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Y\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "A X\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "A Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "A X\n" +
            "A Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "A X\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "A Y\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "C Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "A Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "A Y\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Y\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "A Y\n" +
            "A X\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "A Y\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "A Y\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "A X\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "A Y\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "A X\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "A Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Y\n" +
            "A Y\n" +
            "B X\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "A Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Z\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "A X\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "A X\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Z\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "B X\n" +
            "A Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "A Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "B X\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Y\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Y\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "A Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Y\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "A Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "A X\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "A X\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Y\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "C Z\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "A X\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "A Y\n" +
            "A Z\n" +
            "C Z\n" +
            "A Z";
}
