import java.util.*;

public class RopeBridge {

    private static class Coords {
        int x;
        int y;
        public Coords(int x, int y){
            this.x = x;
            this.y = y;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Coords coords = (Coords) o;
            return x == coords.x && y == coords.y;
        }

        @Override
        public int hashCode() {
            return Objects.hash(x, y);
        }
    }

    private static final int FOLLOWER_COUNT = 9; // 1 for part 1, 9 for part 2
    public static void main(String[] args){
        List<Coords> coords = new ArrayList<>();
        for(int i = 0; i < FOLLOWER_COUNT + 1; i++){
            coords.add(new Coords(0,0));
        }
        Set<Coords> tailVisited = new HashSet<>();
        tailVisited.add(new Coords(coords.get(FOLLOWER_COUNT).x, coords.get(FOLLOWER_COUNT).y));

        for(String step : STEPS.split("\n")){
            String[] parts = step.split(" ");
            int num = Integer.parseInt(parts[1]);
            for(int i = 0; i < num; i++){
                String dir = parts[0];
                Coords head = coords.get(0);
                if("U".equalsIgnoreCase(dir)) {
                    head.y += 1;
                } else if("D".equalsIgnoreCase(dir)){
                    head.y -= 1;
                } else if("L".equalsIgnoreCase(dir)){
                    head.x -=1;
                } else if("R".equalsIgnoreCase(dir)){
                    head.x += 1;
                }
                for(int k = 1; k <= FOLLOWER_COUNT; k++){
                    Coords tail = coords.get(k);
                    int originalX = tail.x;
                    int originalY = tail.y;
                    if(dir.contains("U")){
                        if(head.y > tail.y + 1) {
                            tail.y += 1;
                            updateTailX(head, tail);
                        }
                    }
                    if(dir.contains("D")){
                        if(head.y < tail.y - 1) {
                            tail.y -= 1;
                            updateTailX(head, tail);
                        }
                    }
                    if(dir.contains("L")){
                        if(head.x < tail.x - 1) {
                            tail.x -= 1;
                            updateTailY(head, tail);
                        }
                    }
                    if(dir.contains("R")){
                        if(head.x > tail.x + 1) {
                            tail.x += 1;
                            updateTailY(head, tail);
                        }
                    }

                    dir = "";
                    if(originalY < tail.y){
                        dir += "U";
                    }else if(originalY > tail.y){
                        dir += "D";
                    }
                    if(originalX < tail.x){
                        dir += "R";
                    }else if(originalX > tail.x){
                        dir += "L";
                    }
                    head = tail;
                }


                tailVisited.add(new Coords(coords.get(FOLLOWER_COUNT).x, coords.get(FOLLOWER_COUNT).y));
            }
        }
        System.out.println(tailVisited.size());
    }

    private static void updateTailY(Coords head, Coords tail) {
        if(head.y > tail.y){
            tail.y += 1;
        } else if(head.y < tail.y){
            tail.y -= 1;
        }
    }

    private static void updateTailX(Coords head, Coords tail) {
        if(head.x > tail.x){
            tail.x += 1;
        } else if(head.x < tail.x){
            tail.x -= 1;
        }
    }

    private static final String SAMPLE_STEPS =
            "R 4\n" +
            "U 4\n" +
            "L 3\n" +
            "D 1\n" +
            "R 4\n" +
            "D 1\n" +
            "L 5\n" +
            "R 2";

    private static final String LARGER_SAMPLE =
            "R 5\n" +
            "U 8\n" +
            "L 8\n" +
            "D 3\n" +
            "R 17\n" +
            "D 10\n" +
            "L 25\n" +
            "U 20";

    private static final String STEPS =
            "U 2\n" +
                    "D 2\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "D 1\n" +
                    "L 2\n" +
                    "R 1\n" +
                    "L 2\n" +
                    "U 2\n" +
                    "L 1\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "R 1\n" +
                    "U 2\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "U 1\n" +
                    "L 2\n" +
                    "D 1\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "R 1\n" +
                    "D 1\n" +
                    "U 2\n" +
                    "D 2\n" +
                    "U 1\n" +
                    "R 2\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "U 1\n" +
                    "D 1\n" +
                    "R 1\n" +
                    "L 2\n" +
                    "U 2\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "R 1\n" +
                    "D 1\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "U 2\n" +
                    "R 2\n" +
                    "D 2\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "U 1\n" +
                    "R 2\n" +
                    "U 2\n" +
                    "R 2\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "U 1\n" +
                    "R 2\n" +
                    "D 1\n" +
                    "U 2\n" +
                    "L 1\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "R 2\n" +
                    "U 1\n" +
                    "R 2\n" +
                    "D 1\n" +
                    "L 2\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "U 1\n" +
                    "L 1\n" +
                    "D 2\n" +
                    "L 2\n" +
                    "D 1\n" +
                    "R 2\n" +
                    "D 1\n" +
                    "R 2\n" +
                    "U 1\n" +
                    "D 1\n" +
                    "L 1\n" +
                    "R 1\n" +
                    "L 2\n" +
                    "R 1\n" +
                    "U 1\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "R 1\n" +
                    "U 2\n" +
                    "L 2\n" +
                    "D 1\n" +
                    "U 1\n" +
                    "D 2\n" +
                    "U 2\n" +
                    "R 2\n" +
                    "U 2\n" +
                    "R 1\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "R 2\n" +
                    "D 2\n" +
                    "U 1\n" +
                    "D 1\n" +
                    "R 2\n" +
                    "U 1\n" +
                    "R 2\n" +
                    "L 1\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "U 1\n" +
                    "R 3\n" +
                    "D 1\n" +
                    "R 1\n" +
                    "L 3\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "D 1\n" +
                    "R 3\n" +
                    "L 2\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "U 3\n" +
                    "D 3\n" +
                    "L 1\n" +
                    "D 1\n" +
                    "L 3\n" +
                    "D 1\n" +
                    "U 3\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "L 2\n" +
                    "D 3\n" +
                    "R 1\n" +
                    "U 2\n" +
                    "L 2\n" +
                    "U 1\n" +
                    "L 1\n" +
                    "U 2\n" +
                    "D 2\n" +
                    "U 1\n" +
                    "L 1\n" +
                    "D 3\n" +
                    "R 1\n" +
                    "D 3\n" +
                    "R 1\n" +
                    "D 1\n" +
                    "U 1\n" +
                    "L 2\n" +
                    "U 3\n" +
                    "D 2\n" +
                    "U 1\n" +
                    "R 3\n" +
                    "D 1\n" +
                    "U 3\n" +
                    "L 3\n" +
                    "U 1\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "U 1\n" +
                    "L 1\n" +
                    "D 2\n" +
                    "L 2\n" +
                    "U 2\n" +
                    "L 1\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "U 2\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "L 1\n" +
                    "U 2\n" +
                    "L 2\n" +
                    "R 3\n" +
                    "L 3\n" +
                    "D 1\n" +
                    "R 3\n" +
                    "L 3\n" +
                    "D 2\n" +
                    "U 3\n" +
                    "L 3\n" +
                    "D 2\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "D 2\n" +
                    "U 2\n" +
                    "L 3\n" +
                    "R 1\n" +
                    "U 2\n" +
                    "L 1\n" +
                    "D 3\n" +
                    "U 2\n" +
                    "D 3\n" +
                    "L 2\n" +
                    "D 3\n" +
                    "U 1\n" +
                    "D 3\n" +
                    "U 3\n" +
                    "L 3\n" +
                    "D 2\n" +
                    "L 3\n" +
                    "R 2\n" +
                    "D 3\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "U 3\n" +
                    "D 2\n" +
                    "L 2\n" +
                    "D 1\n" +
                    "R 1\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "L 3\n" +
                    "U 3\n" +
                    "L 1\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "L 2\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "D 1\n" +
                    "L 4\n" +
                    "D 2\n" +
                    "R 3\n" +
                    "U 4\n" +
                    "R 4\n" +
                    "U 1\n" +
                    "D 4\n" +
                    "U 4\n" +
                    "D 4\n" +
                    "U 2\n" +
                    "R 3\n" +
                    "U 3\n" +
                    "R 4\n" +
                    "U 3\n" +
                    "L 2\n" +
                    "R 1\n" +
                    "U 4\n" +
                    "D 4\n" +
                    "R 2\n" +
                    "D 4\n" +
                    "R 2\n" +
                    "U 2\n" +
                    "D 1\n" +
                    "R 1\n" +
                    "L 3\n" +
                    "R 2\n" +
                    "D 3\n" +
                    "R 3\n" +
                    "U 1\n" +
                    "D 2\n" +
                    "R 4\n" +
                    "U 1\n" +
                    "D 4\n" +
                    "R 1\n" +
                    "U 1\n" +
                    "D 2\n" +
                    "U 4\n" +
                    "D 3\n" +
                    "L 1\n" +
                    "D 4\n" +
                    "L 2\n" +
                    "D 2\n" +
                    "R 3\n" +
                    "L 1\n" +
                    "U 4\n" +
                    "L 4\n" +
                    "U 3\n" +
                    "D 3\n" +
                    "L 2\n" +
                    "D 3\n" +
                    "U 1\n" +
                    "R 4\n" +
                    "D 3\n" +
                    "L 3\n" +
                    "D 4\n" +
                    "L 1\n" +
                    "D 2\n" +
                    "U 4\n" +
                    "L 2\n" +
                    "D 1\n" +
                    "R 3\n" +
                    "D 4\n" +
                    "U 3\n" +
                    "D 4\n" +
                    "U 2\n" +
                    "L 2\n" +
                    "R 3\n" +
                    "L 4\n" +
                    "R 2\n" +
                    "L 4\n" +
                    "U 3\n" +
                    "L 4\n" +
                    "D 3\n" +
                    "U 4\n" +
                    "L 2\n" +
                    "U 3\n" +
                    "R 2\n" +
                    "D 2\n" +
                    "U 1\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "R 4\n" +
                    "D 3\n" +
                    "L 1\n" +
                    "D 3\n" +
                    "U 2\n" +
                    "L 4\n" +
                    "D 4\n" +
                    "L 4\n" +
                    "R 3\n" +
                    "L 3\n" +
                    "U 2\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "L 4\n" +
                    "D 2\n" +
                    "L 3\n" +
                    "U 3\n" +
                    "D 1\n" +
                    "L 2\n" +
                    "R 3\n" +
                    "U 4\n" +
                    "R 1\n" +
                    "U 3\n" +
                    "D 4\n" +
                    "L 2\n" +
                    "U 2\n" +
                    "L 2\n" +
                    "R 5\n" +
                    "D 5\n" +
                    "U 3\n" +
                    "R 4\n" +
                    "L 4\n" +
                    "U 5\n" +
                    "D 3\n" +
                    "U 2\n" +
                    "L 5\n" +
                    "U 1\n" +
                    "R 3\n" +
                    "L 3\n" +
                    "U 4\n" +
                    "L 3\n" +
                    "D 5\n" +
                    "U 2\n" +
                    "R 1\n" +
                    "U 4\n" +
                    "R 5\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "U 3\n" +
                    "R 5\n" +
                    "D 2\n" +
                    "U 3\n" +
                    "D 5\n" +
                    "U 2\n" +
                    "D 2\n" +
                    "U 2\n" +
                    "L 4\n" +
                    "U 5\n" +
                    "R 4\n" +
                    "U 4\n" +
                    "L 3\n" +
                    "U 5\n" +
                    "R 4\n" +
                    "L 4\n" +
                    "D 5\n" +
                    "R 4\n" +
                    "D 4\n" +
                    "L 2\n" +
                    "R 3\n" +
                    "L 5\n" +
                    "D 3\n" +
                    "U 2\n" +
                    "D 4\n" +
                    "R 1\n" +
                    "U 5\n" +
                    "R 4\n" +
                    "D 1\n" +
                    "U 1\n" +
                    "L 1\n" +
                    "U 3\n" +
                    "D 2\n" +
                    "U 4\n" +
                    "D 3\n" +
                    "U 5\n" +
                    "R 2\n" +
                    "U 5\n" +
                    "L 1\n" +
                    "R 5\n" +
                    "U 5\n" +
                    "R 4\n" +
                    "D 3\n" +
                    "R 1\n" +
                    "D 3\n" +
                    "U 3\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "D 5\n" +
                    "U 4\n" +
                    "R 3\n" +
                    "D 3\n" +
                    "L 2\n" +
                    "U 1\n" +
                    "L 2\n" +
                    "U 5\n" +
                    "D 5\n" +
                    "U 2\n" +
                    "D 4\n" +
                    "L 2\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "D 4\n" +
                    "U 2\n" +
                    "D 4\n" +
                    "R 1\n" +
                    "U 1\n" +
                    "D 4\n" +
                    "L 3\n" +
                    "D 3\n" +
                    "U 2\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "D 5\n" +
                    "R 1\n" +
                    "L 2\n" +
                    "D 5\n" +
                    "U 5\n" +
                    "L 3\n" +
                    "D 1\n" +
                    "R 2\n" +
                    "L 2\n" +
                    "U 1\n" +
                    "L 2\n" +
                    "D 5\n" +
                    "L 1\n" +
                    "R 2\n" +
                    "D 4\n" +
                    "U 6\n" +
                    "L 4\n" +
                    "R 5\n" +
                    "D 4\n" +
                    "U 2\n" +
                    "R 1\n" +
                    "D 4\n" +
                    "L 2\n" +
                    "R 5\n" +
                    "L 6\n" +
                    "R 2\n" +
                    "U 6\n" +
                    "R 5\n" +
                    "D 1\n" +
                    "U 1\n" +
                    "L 6\n" +
                    "R 2\n" +
                    "L 6\n" +
                    "D 3\n" +
                    "L 2\n" +
                    "R 6\n" +
                    "U 6\n" +
                    "L 1\n" +
                    "D 3\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "R 4\n" +
                    "L 4\n" +
                    "U 6\n" +
                    "L 3\n" +
                    "D 1\n" +
                    "U 1\n" +
                    "L 4\n" +
                    "R 3\n" +
                    "D 3\n" +
                    "R 6\n" +
                    "D 3\n" +
                    "L 4\n" +
                    "R 5\n" +
                    "L 5\n" +
                    "D 3\n" +
                    "U 3\n" +
                    "D 6\n" +
                    "R 4\n" +
                    "D 5\n" +
                    "L 2\n" +
                    "D 1\n" +
                    "R 4\n" +
                    "L 6\n" +
                    "R 5\n" +
                    "U 4\n" +
                    "D 5\n" +
                    "L 3\n" +
                    "D 1\n" +
                    "L 6\n" +
                    "D 5\n" +
                    "L 3\n" +
                    "U 3\n" +
                    "R 4\n" +
                    "L 4\n" +
                    "D 6\n" +
                    "R 3\n" +
                    "L 1\n" +
                    "R 1\n" +
                    "U 4\n" +
                    "D 6\n" +
                    "L 3\n" +
                    "R 2\n" +
                    "D 1\n" +
                    "L 2\n" +
                    "U 3\n" +
                    "D 3\n" +
                    "L 5\n" +
                    "U 6\n" +
                    "L 5\n" +
                    "D 5\n" +
                    "R 5\n" +
                    "U 6\n" +
                    "D 2\n" +
                    "U 2\n" +
                    "R 5\n" +
                    "U 6\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "L 3\n" +
                    "U 1\n" +
                    "L 6\n" +
                    "U 1\n" +
                    "R 3\n" +
                    "L 3\n" +
                    "D 4\n" +
                    "U 2\n" +
                    "R 3\n" +
                    "L 1\n" +
                    "D 3\n" +
                    "R 5\n" +
                    "L 2\n" +
                    "D 3\n" +
                    "L 2\n" +
                    "U 6\n" +
                    "R 5\n" +
                    "U 5\n" +
                    "L 1\n" +
                    "U 5\n" +
                    "L 6\n" +
                    "D 4\n" +
                    "U 2\n" +
                    "L 5\n" +
                    "U 3\n" +
                    "D 2\n" +
                    "U 4\n" +
                    "D 4\n" +
                    "U 2\n" +
                    "R 5\n" +
                    "L 4\n" +
                    "D 3\n" +
                    "R 6\n" +
                    "D 1\n" +
                    "R 4\n" +
                    "U 5\n" +
                    "L 7\n" +
                    "D 2\n" +
                    "R 6\n" +
                    "U 4\n" +
                    "L 5\n" +
                    "D 5\n" +
                    "L 2\n" +
                    "D 1\n" +
                    "R 4\n" +
                    "D 6\n" +
                    "L 5\n" +
                    "D 4\n" +
                    "R 7\n" +
                    "U 4\n" +
                    "D 7\n" +
                    "U 4\n" +
                    "R 3\n" +
                    "L 7\n" +
                    "R 7\n" +
                    "D 3\n" +
                    "R 5\n" +
                    "U 2\n" +
                    "R 3\n" +
                    "D 5\n" +
                    "R 5\n" +
                    "U 4\n" +
                    "D 2\n" +
                    "U 5\n" +
                    "R 1\n" +
                    "U 5\n" +
                    "R 5\n" +
                    "U 7\n" +
                    "R 4\n" +
                    "D 6\n" +
                    "L 1\n" +
                    "U 3\n" +
                    "D 4\n" +
                    "U 3\n" +
                    "D 7\n" +
                    "U 2\n" +
                    "L 4\n" +
                    "D 6\n" +
                    "R 7\n" +
                    "U 1\n" +
                    "L 6\n" +
                    "D 4\n" +
                    "R 6\n" +
                    "D 4\n" +
                    "U 5\n" +
                    "L 4\n" +
                    "D 6\n" +
                    "L 5\n" +
                    "D 1\n" +
                    "L 5\n" +
                    "U 3\n" +
                    "L 3\n" +
                    "U 2\n" +
                    "R 6\n" +
                    "U 3\n" +
                    "D 4\n" +
                    "U 4\n" +
                    "L 1\n" +
                    "D 3\n" +
                    "L 3\n" +
                    "R 6\n" +
                    "U 2\n" +
                    "L 3\n" +
                    "D 7\n" +
                    "L 2\n" +
                    "U 7\n" +
                    "L 4\n" +
                    "U 4\n" +
                    "D 7\n" +
                    "L 4\n" +
                    "D 3\n" +
                    "L 3\n" +
                    "D 3\n" +
                    "U 1\n" +
                    "D 5\n" +
                    "L 1\n" +
                    "R 4\n" +
                    "D 7\n" +
                    "L 7\n" +
                    "D 6\n" +
                    "R 3\n" +
                    "U 1\n" +
                    "R 6\n" +
                    "L 4\n" +
                    "D 6\n" +
                    "R 5\n" +
                    "U 7\n" +
                    "L 6\n" +
                    "R 6\n" +
                    "L 3\n" +
                    "D 4\n" +
                    "U 1\n" +
                    "R 2\n" +
                    "L 1\n" +
                    "R 1\n" +
                    "U 4\n" +
                    "D 1\n" +
                    "L 4\n" +
                    "R 2\n" +
                    "U 4\n" +
                    "R 3\n" +
                    "D 1\n" +
                    "U 3\n" +
                    "R 4\n" +
                    "L 2\n" +
                    "U 4\n" +
                    "L 3\n" +
                    "D 7\n" +
                    "R 6\n" +
                    "U 4\n" +
                    "L 4\n" +
                    "D 7\n" +
                    "R 6\n" +
                    "D 7\n" +
                    "L 5\n" +
                    "R 5\n" +
                    "D 7\n" +
                    "R 4\n" +
                    "D 1\n" +
                    "L 6\n" +
                    "U 8\n" +
                    "L 4\n" +
                    "U 2\n" +
                    "L 6\n" +
                    "R 1\n" +
                    "L 5\n" +
                    "U 5\n" +
                    "D 3\n" +
                    "L 8\n" +
                    "R 3\n" +
                    "L 3\n" +
                    "R 5\n" +
                    "U 4\n" +
                    "R 6\n" +
                    "D 4\n" +
                    "U 1\n" +
                    "L 2\n" +
                    "R 8\n" +
                    "D 7\n" +
                    "U 3\n" +
                    "D 4\n" +
                    "L 8\n" +
                    "U 6\n" +
                    "L 5\n" +
                    "R 1\n" +
                    "U 1\n" +
                    "R 4\n" +
                    "U 5\n" +
                    "D 2\n" +
                    "R 2\n" +
                    "U 2\n" +
                    "L 1\n" +
                    "U 8\n" +
                    "D 4\n" +
                    "R 7\n" +
                    "U 3\n" +
                    "D 6\n" +
                    "R 6\n" +
                    "L 3\n" +
                    "R 8\n" +
                    "D 7\n" +
                    "U 2\n" +
                    "R 5\n" +
                    "L 3\n" +
                    "U 1\n" +
                    "D 6\n" +
                    "R 1\n" +
                    "D 3\n" +
                    "L 2\n" +
                    "U 2\n" +
                    "D 8\n" +
                    "U 8\n" +
                    "L 8\n" +
                    "U 5\n" +
                    "D 6\n" +
                    "U 6\n" +
                    "L 6\n" +
                    "U 6\n" +
                    "D 5\n" +
                    "R 8\n" +
                    "L 7\n" +
                    "D 6\n" +
                    "R 1\n" +
                    "D 4\n" +
                    "L 1\n" +
                    "U 7\n" +
                    "R 3\n" +
                    "L 2\n" +
                    "D 6\n" +
                    "R 6\n" +
                    "D 7\n" +
                    "L 6\n" +
                    "U 5\n" +
                    "R 4\n" +
                    "D 7\n" +
                    "U 7\n" +
                    "D 5\n" +
                    "L 4\n" +
                    "R 6\n" +
                    "D 3\n" +
                    "L 6\n" +
                    "U 2\n" +
                    "D 7\n" +
                    "R 7\n" +
                    "U 5\n" +
                    "D 3\n" +
                    "U 2\n" +
                    "L 1\n" +
                    "D 2\n" +
                    "U 4\n" +
                    "L 1\n" +
                    "R 3\n" +
                    "L 6\n" +
                    "U 9\n" +
                    "D 8\n" +
                    "L 3\n" +
                    "R 3\n" +
                    "D 4\n" +
                    "R 3\n" +
                    "U 6\n" +
                    "L 7\n" +
                    "D 8\n" +
                    "R 9\n" +
                    "D 1\n" +
                    "L 3\n" +
                    "R 6\n" +
                    "D 4\n" +
                    "L 3\n" +
                    "U 6\n" +
                    "L 7\n" +
                    "R 7\n" +
                    "U 9\n" +
                    "L 9\n" +
                    "R 7\n" +
                    "U 8\n" +
                    "R 7\n" +
                    "U 7\n" +
                    "D 1\n" +
                    "L 9\n" +
                    "R 6\n" +
                    "U 4\n" +
                    "D 6\n" +
                    "L 8\n" +
                    "R 7\n" +
                    "D 6\n" +
                    "U 5\n" +
                    "R 6\n" +
                    "D 8\n" +
                    "L 2\n" +
                    "D 5\n" +
                    "R 9\n" +
                    "U 9\n" +
                    "L 7\n" +
                    "U 2\n" +
                    "R 7\n" +
                    "L 6\n" +
                    "U 6\n" +
                    "D 5\n" +
                    "L 8\n" +
                    "D 7\n" +
                    "L 8\n" +
                    "D 9\n" +
                    "R 7\n" +
                    "L 5\n" +
                    "D 9\n" +
                    "L 7\n" +
                    "R 2\n" +
                    "L 6\n" +
                    "R 9\n" +
                    "D 8\n" +
                    "R 8\n" +
                    "U 7\n" +
                    "R 4\n" +
                    "L 6\n" +
                    "R 1\n" +
                    "U 9\n" +
                    "D 2\n" +
                    "R 7\n" +
                    "D 5\n" +
                    "R 4\n" +
                    "D 1\n" +
                    "U 7\n" +
                    "D 5\n" +
                    "R 4\n" +
                    "U 2\n" +
                    "D 5\n" +
                    "L 9\n" +
                    "R 6\n" +
                    "U 7\n" +
                    "D 5\n" +
                    "U 4\n" +
                    "D 6\n" +
                    "L 3\n" +
                    "R 6\n" +
                    "U 3\n" +
                    "R 9\n" +
                    "L 9\n" +
                    "U 4\n" +
                    "D 1\n" +
                    "U 3\n" +
                    "R 7\n" +
                    "D 8\n" +
                    "R 9\n" +
                    "U 1\n" +
                    "R 1\n" +
                    "U 4\n" +
                    "D 7\n" +
                    "R 1\n" +
                    "L 1\n" +
                    "R 8\n" +
                    "D 1\n" +
                    "U 1\n" +
                    "L 3\n" +
                    "U 2\n" +
                    "D 6\n" +
                    "R 6\n" +
                    "L 1\n" +
                    "R 9\n" +
                    "L 2\n" +
                    "D 3\n" +
                    "U 8\n" +
                    "D 9\n" +
                    "U 1\n" +
                    "L 10\n" +
                    "U 10\n" +
                    "D 8\n" +
                    "U 9\n" +
                    "L 3\n" +
                    "R 2\n" +
                    "D 3\n" +
                    "U 4\n" +
                    "L 2\n" +
                    "R 10\n" +
                    "L 9\n" +
                    "U 5\n" +
                    "L 5\n" +
                    "D 4\n" +
                    "L 7\n" +
                    "U 1\n" +
                    "L 1\n" +
                    "R 1\n" +
                    "L 7\n" +
                    "D 7\n" +
                    "U 7\n" +
                    "L 3\n" +
                    "U 10\n" +
                    "R 7\n" +
                    "U 9\n" +
                    "L 6\n" +
                    "R 2\n" +
                    "D 9\n" +
                    "L 10\n" +
                    "D 9\n" +
                    "L 9\n" +
                    "R 5\n" +
                    "L 5\n" +
                    "R 8\n" +
                    "D 9\n" +
                    "R 1\n" +
                    "D 6\n" +
                    "L 1\n" +
                    "U 9\n" +
                    "R 3\n" +
                    "L 10\n" +
                    "D 10\n" +
                    "L 5\n" +
                    "D 10\n" +
                    "R 3\n" +
                    "U 7\n" +
                    "D 6\n" +
                    "U 7\n" +
                    "D 3\n" +
                    "R 5\n" +
                    "D 5\n" +
                    "L 6\n" +
                    "D 4\n" +
                    "U 7\n" +
                    "D 7\n" +
                    "R 9\n" +
                    "U 10\n" +
                    "R 4\n" +
                    "U 1\n" +
                    "R 1\n" +
                    "U 8\n" +
                    "R 3\n" +
                    "U 10\n" +
                    "R 6\n" +
                    "L 1\n" +
                    "U 3\n" +
                    "R 9\n" +
                    "U 2\n" +
                    "D 8\n" +
                    "R 5\n" +
                    "D 3\n" +
                    "R 3\n" +
                    "U 9\n" +
                    "R 6\n" +
                    "L 8\n" +
                    "R 2\n" +
                    "L 5\n" +
                    "R 2\n" +
                    "L 10\n" +
                    "D 2\n" +
                    "L 3\n" +
                    "U 1\n" +
                    "D 10\n" +
                    "L 5\n" +
                    "R 10\n" +
                    "D 7\n" +
                    "L 2\n" +
                    "R 7\n" +
                    "U 6\n" +
                    "D 4\n" +
                    "L 8\n" +
                    "D 8\n" +
                    "U 3\n" +
                    "R 2\n" +
                    "U 10\n" +
                    "D 8\n" +
                    "U 7\n" +
                    "D 9\n" +
                    "U 4\n" +
                    "R 9\n" +
                    "L 2\n" +
                    "R 8\n" +
                    "U 9\n" +
                    "R 10\n" +
                    "U 10\n" +
                    "D 8\n" +
                    "R 8\n" +
                    "U 2\n" +
                    "L 7\n" +
                    "U 3\n" +
                    "L 1\n" +
                    "D 7\n" +
                    "R 1\n" +
                    "U 2\n" +
                    "R 8\n" +
                    "U 4\n" +
                    "D 4\n" +
                    "L 2\n" +
                    "U 9\n" +
                    "L 7\n" +
                    "D 7\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "D 9\n" +
                    "L 11\n" +
                    "U 4\n" +
                    "L 3\n" +
                    "D 7\n" +
                    "U 7\n" +
                    "R 6\n" +
                    "D 7\n" +
                    "U 11\n" +
                    "R 4\n" +
                    "L 3\n" +
                    "R 2\n" +
                    "U 9\n" +
                    "L 1\n" +
                    "U 11\n" +
                    "D 7\n" +
                    "R 10\n" +
                    "D 10\n" +
                    "U 7\n" +
                    "L 1\n" +
                    "U 8\n" +
                    "L 2\n" +
                    "D 11\n" +
                    "L 6\n" +
                    "D 1\n" +
                    "L 8\n" +
                    "D 9\n" +
                    "U 9\n" +
                    "R 5\n" +
                    "L 4\n" +
                    "D 7\n" +
                    "U 8\n" +
                    "L 5\n" +
                    "D 3\n" +
                    "R 6\n" +
                    "L 5\n" +
                    "R 7\n" +
                    "L 7\n" +
                    "D 7\n" +
                    "L 10\n" +
                    "U 4\n" +
                    "L 1\n" +
                    "U 9\n" +
                    "D 2\n" +
                    "R 2\n" +
                    "U 4\n" +
                    "D 3\n" +
                    "R 9\n" +
                    "D 11\n" +
                    "U 10\n" +
                    "L 3\n" +
                    "R 9\n" +
                    "U 6\n" +
                    "L 1\n" +
                    "R 9\n" +
                    "L 8\n" +
                    "U 2\n" +
                    "L 3\n" +
                    "U 9\n" +
                    "D 2\n" +
                    "L 4\n" +
                    "D 5\n" +
                    "U 4\n" +
                    "L 5\n" +
                    "D 11\n" +
                    "L 6\n" +
                    "U 10\n" +
                    "D 9\n" +
                    "U 3\n" +
                    "L 9\n" +
                    "U 11\n" +
                    "D 3\n" +
                    "L 7\n" +
                    "D 4\n" +
                    "L 8\n" +
                    "U 5\n" +
                    "D 10\n" +
                    "L 7\n" +
                    "U 10\n" +
                    "L 10\n" +
                    "U 4\n" +
                    "D 10\n" +
                    "L 7\n" +
                    "R 2\n" +
                    "D 3\n" +
                    "L 6\n" +
                    "R 5\n" +
                    "U 11\n" +
                    "D 4\n" +
                    "U 6\n" +
                    "D 9\n" +
                    "R 2\n" +
                    "L 9\n" +
                    "U 9\n" +
                    "R 11\n" +
                    "U 9\n" +
                    "L 10\n" +
                    "R 8\n" +
                    "L 5\n" +
                    "R 2\n" +
                    "L 12\n" +
                    "R 8\n" +
                    "U 10\n" +
                    "R 7\n" +
                    "D 7\n" +
                    "U 3\n" +
                    "L 10\n" +
                    "U 10\n" +
                    "L 11\n" +
                    "U 1\n" +
                    "R 8\n" +
                    "D 4\n" +
                    "R 3\n" +
                    "D 7\n" +
                    "U 9\n" +
                    "L 2\n" +
                    "R 9\n" +
                    "L 8\n" +
                    "R 6\n" +
                    "L 7\n" +
                    "D 11\n" +
                    "U 12\n" +
                    "D 6\n" +
                    "U 7\n" +
                    "L 11\n" +
                    "D 1\n" +
                    "U 9\n" +
                    "R 7\n" +
                    "L 3\n" +
                    "D 3\n" +
                    "U 5\n" +
                    "R 5\n" +
                    "L 3\n" +
                    "R 11\n" +
                    "L 2\n" +
                    "U 9\n" +
                    "D 9\n" +
                    "R 8\n" +
                    "U 7\n" +
                    "D 5\n" +
                    "L 9\n" +
                    "D 2\n" +
                    "L 1\n" +
                    "R 5\n" +
                    "U 9\n" +
                    "R 10\n" +
                    "U 12\n" +
                    "L 9\n" +
                    "D 12\n" +
                    "R 5\n" +
                    "U 2\n" +
                    "L 7\n" +
                    "R 6\n" +
                    "L 1\n" +
                    "U 12\n" +
                    "L 10\n" +
                    "R 11\n" +
                    "D 1\n" +
                    "L 8\n" +
                    "U 6\n" +
                    "D 10\n" +
                    "R 10\n" +
                    "L 1\n" +
                    "U 11\n" +
                    "D 2\n" +
                    "R 6\n" +
                    "U 1\n" +
                    "R 4\n" +
                    "D 1\n" +
                    "R 6\n" +
                    "U 12\n" +
                    "D 1\n" +
                    "L 1\n" +
                    "U 4\n" +
                    "D 4\n" +
                    "U 12\n" +
                    "D 12\n" +
                    "L 5\n" +
                    "R 10\n" +
                    "D 4\n" +
                    "R 1\n" +
                    "D 8\n" +
                    "U 6\n" +
                    "R 7\n" +
                    "D 12\n" +
                    "U 9\n" +
                    "D 6\n" +
                    "U 6\n" +
                    "D 1\n" +
                    "R 2\n" +
                    "L 7\n" +
                    "R 5\n" +
                    "L 4\n" +
                    "U 1\n" +
                    "L 10\n" +
                    "R 8\n" +
                    "L 12\n" +
                    "D 11\n" +
                    "U 2\n" +
                    "L 10\n" +
                    "D 12\n" +
                    "R 9\n" +
                    "D 1\n" +
                    "U 7\n" +
                    "L 5\n" +
                    "D 4\n" +
                    "U 12\n" +
                    "L 12\n" +
                    "D 11\n" +
                    "U 11\n" +
                    "L 6\n" +
                    "D 2\n" +
                    "R 11\n" +
                    "L 1\n" +
                    "U 10\n" +
                    "L 12\n" +
                    "D 11\n" +
                    "R 8\n" +
                    "D 2\n" +
                    "L 10\n" +
                    "R 4\n" +
                    "L 10\n" +
                    "D 13\n" +
                    "L 10\n" +
                    "D 5\n" +
                    "U 9\n" +
                    "L 3\n" +
                    "D 2\n" +
                    "U 3\n" +
                    "D 11\n" +
                    "L 7\n" +
                    "D 11\n" +
                    "U 4\n" +
                    "D 11\n" +
                    "U 8\n" +
                    "L 5\n" +
                    "U 6\n" +
                    "L 3\n" +
                    "U 3\n" +
                    "R 8\n" +
                    "D 10\n" +
                    "R 1\n" +
                    "D 13\n" +
                    "L 7\n" +
                    "D 7\n" +
                    "R 1\n" +
                    "D 2\n" +
                    "L 3\n" +
                    "D 5\n" +
                    "R 5\n" +
                    "L 5\n" +
                    "U 7\n" +
                    "L 4\n" +
                    "D 1\n" +
                    "L 11\n" +
                    "R 10\n" +
                    "U 8\n" +
                    "D 9\n" +
                    "U 8\n" +
                    "R 11\n" +
                    "L 1\n" +
                    "R 6\n" +
                    "D 6\n" +
                    "U 4\n" +
                    "L 2\n" +
                    "D 11\n" +
                    "U 10\n" +
                    "D 4\n" +
                    "L 11\n" +
                    "R 5\n" +
                    "U 2\n" +
                    "D 10\n" +
                    "U 12\n" +
                    "L 12\n" +
                    "D 11\n" +
                    "L 12\n" +
                    "D 10\n" +
                    "L 4\n" +
                    "U 7\n" +
                    "D 1\n" +
                    "R 4\n" +
                    "L 10\n" +
                    "D 9\n" +
                    "R 5\n" +
                    "D 3\n" +
                    "L 3\n" +
                    "D 5\n" +
                    "R 9\n" +
                    "D 10\n" +
                    "L 8\n" +
                    "R 6\n" +
                    "D 4\n" +
                    "U 5\n" +
                    "R 11\n" +
                    "U 13\n" +
                    "R 10\n" +
                    "U 11\n" +
                    "R 9\n" +
                    "U 4\n" +
                    "D 8\n" +
                    "U 4\n" +
                    "D 6\n" +
                    "R 12\n" +
                    "U 12\n" +
                    "R 9\n" +
                    "U 12\n" +
                    "L 13\n" +
                    "U 6\n" +
                    "D 10\n" +
                    "R 2\n" +
                    "L 5\n" +
                    "U 3\n" +
                    "L 8\n" +
                    "R 11\n" +
                    "D 13\n" +
                    "R 6\n" +
                    "U 13\n" +
                    "L 3\n" +
                    "U 3\n" +
                    "D 4\n" +
                    "L 11\n" +
                    "U 14\n" +
                    "D 13\n" +
                    "U 1\n" +
                    "L 8\n" +
                    "U 13\n" +
                    "R 14\n" +
                    "U 2\n" +
                    "L 13\n" +
                    "R 1\n" +
                    "U 1\n" +
                    "L 13\n" +
                    "R 4\n" +
                    "D 10\n" +
                    "R 10\n" +
                    "D 14\n" +
                    "R 7\n" +
                    "D 10\n" +
                    "L 2\n" +
                    "R 7\n" +
                    "U 10\n" +
                    "R 13\n" +
                    "D 7\n" +
                    "U 11\n" +
                    "D 13\n" +
                    "L 7\n" +
                    "U 8\n" +
                    "L 4\n" +
                    "D 7\n" +
                    "L 2\n" +
                    "R 2\n" +
                    "L 7\n" +
                    "D 13\n" +
                    "U 2\n" +
                    "R 10\n" +
                    "U 2\n" +
                    "L 6\n" +
                    "R 11\n" +
                    "D 11\n" +
                    "L 13\n" +
                    "D 13\n" +
                    "L 14\n" +
                    "R 4\n" +
                    "L 7\n" +
                    "D 7\n" +
                    "R 11\n" +
                    "U 10\n" +
                    "D 3\n" +
                    "R 4\n" +
                    "L 2\n" +
                    "R 9\n" +
                    "U 7\n" +
                    "L 1\n" +
                    "R 5\n" +
                    "L 3\n" +
                    "U 8\n" +
                    "R 6\n" +
                    "U 10\n" +
                    "L 3\n" +
                    "R 12\n" +
                    "U 13\n" +
                    "D 3\n" +
                    "R 7\n" +
                    "D 1\n" +
                    "U 7\n" +
                    "R 13\n" +
                    "D 1\n" +
                    "R 10\n" +
                    "L 8\n" +
                    "R 8\n" +
                    "L 4\n" +
                    "R 9\n" +
                    "L 5\n" +
                    "D 13\n" +
                    "L 3\n" +
                    "U 8\n" +
                    "L 13\n" +
                    "U 4\n" +
                    "R 3\n" +
                    "U 2\n" +
                    "R 7\n" +
                    "D 9\n" +
                    "R 5\n" +
                    "U 4\n" +
                    "R 5\n" +
                    "D 7\n" +
                    "L 14\n" +
                    "R 13\n" +
                    "D 3\n" +
                    "L 12\n" +
                    "D 7\n" +
                    "U 5\n" +
                    "L 8\n" +
                    "D 10\n" +
                    "U 14\n" +
                    "D 8\n" +
                    "R 12\n" +
                    "U 3\n" +
                    "L 9\n" +
                    "R 7\n" +
                    "U 9\n" +
                    "R 5\n" +
                    "L 6\n" +
                    "U 13\n" +
                    "R 6\n" +
                    "L 8\n" +
                    "R 12\n" +
                    "D 13\n" +
                    "U 6\n" +
                    "L 12\n" +
                    "U 15\n" +
                    "D 10\n" +
                    "U 15\n" +
                    "D 7\n" +
                    "R 14\n" +
                    "D 5\n" +
                    "R 9\n" +
                    "U 11\n" +
                    "L 8\n" +
                    "D 9\n" +
                    "R 3\n" +
                    "U 3\n" +
                    "R 8\n" +
                    "D 6\n" +
                    "L 3\n" +
                    "R 9\n" +
                    "U 12\n" +
                    "L 12\n" +
                    "D 3\n" +
                    "U 13\n" +
                    "L 4\n" +
                    "R 3\n" +
                    "D 6\n" +
                    "R 12\n" +
                    "D 15\n" +
                    "L 3\n" +
                    "D 9\n" +
                    "R 9\n" +
                    "D 11\n" +
                    "L 6\n" +
                    "D 6\n" +
                    "L 3\n" +
                    "U 2\n" +
                    "D 6\n" +
                    "L 4\n" +
                    "D 3\n" +
                    "U 5\n" +
                    "D 1\n" +
                    "U 11\n" +
                    "R 11\n" +
                    "U 5\n" +
                    "L 12\n" +
                    "U 14\n" +
                    "R 1\n" +
                    "D 10\n" +
                    "L 8\n" +
                    "R 12\n" +
                    "L 5\n" +
                    "U 2\n" +
                    "D 2\n" +
                    "U 8\n" +
                    "D 5\n" +
                    "U 14\n" +
                    "D 2\n" +
                    "L 6\n" +
                    "R 5\n" +
                    "D 10\n" +
                    "L 10\n" +
                    "U 2\n" +
                    "R 2\n" +
                    "U 2\n" +
                    "L 15\n" +
                    "R 14\n" +
                    "D 12\n" +
                    "L 4\n" +
                    "U 2\n" +
                    "D 10\n" +
                    "R 14\n" +
                    "U 13\n" +
                    "R 9\n" +
                    "L 4\n" +
                    "U 15\n" +
                    "D 8\n" +
                    "R 4\n" +
                    "D 9\n" +
                    "U 1\n" +
                    "R 4\n" +
                    "D 3\n" +
                    "L 3\n" +
                    "D 7\n" +
                    "L 12\n" +
                    "R 8\n" +
                    "D 7\n" +
                    "L 15\n" +
                    "R 12\n" +
                    "U 10\n" +
                    "L 11\n" +
                    "R 1\n" +
                    "U 13\n" +
                    "R 14\n" +
                    "L 14\n" +
                    "D 14\n" +
                    "U 1\n" +
                    "R 1\n" +
                    "U 13\n" +
                    "L 15\n" +
                    "U 11\n" +
                    "D 15\n" +
                    "U 1\n" +
                    "R 15\n" +
                    "L 4\n" +
                    "U 12\n" +
                    "R 8\n" +
                    "U 10\n" +
                    "R 7\n" +
                    "U 3\n" +
                    "L 14\n" +
                    "U 14\n" +
                    "R 8\n" +
                    "D 1\n" +
                    "U 9\n" +
                    "L 3\n" +
                    "U 8\n" +
                    "D 5\n" +
                    "L 12\n" +
                    "U 15\n" +
                    "D 13\n" +
                    "L 11\n" +
                    "R 4\n" +
                    "U 12\n" +
                    "R 7\n" +
                    "L 15\n" +
                    "U 8\n" +
                    "D 7\n" +
                    "L 8\n" +
                    "R 7\n" +
                    "D 1\n" +
                    "L 12\n" +
                    "U 15\n" +
                    "L 15\n" +
                    "U 9\n" +
                    "R 10\n" +
                    "D 8\n" +
                    "U 10\n" +
                    "R 15\n" +
                    "D 3\n" +
                    "R 14\n" +
                    "D 13\n" +
                    "L 3\n" +
                    "R 2\n" +
                    "U 14\n" +
                    "L 3\n" +
                    "R 7\n" +
                    "L 15\n" +
                    "D 4\n" +
                    "R 14\n" +
                    "U 11\n" +
                    "L 2\n" +
                    "U 16\n" +
                    "L 6\n" +
                    "D 4\n" +
                    "L 3\n" +
                    "U 8\n" +
                    "R 16\n" +
                    "U 8\n" +
                    "D 13\n" +
                    "L 11\n" +
                    "U 11\n" +
                    "D 11\n" +
                    "R 14\n" +
                    "D 15\n" +
                    "L 4\n" +
                    "R 13\n" +
                    "U 4\n" +
                    "D 15\n" +
                    "U 10\n" +
                    "D 4\n" +
                    "R 14\n" +
                    "D 5\n" +
                    "U 7\n" +
                    "R 1\n" +
                    "L 6\n" +
                    "U 5\n" +
                    "L 10\n" +
                    "U 15\n" +
                    "L 14\n" +
                    "D 2\n" +
                    "U 5\n" +
                    "R 8\n" +
                    "L 14\n" +
                    "U 3\n" +
                    "R 9\n" +
                    "L 14\n" +
                    "R 8\n" +
                    "D 10\n" +
                    "L 8\n" +
                    "R 9\n" +
                    "L 14\n" +
                    "D 8\n" +
                    "R 16\n" +
                    "U 2\n" +
                    "D 12\n" +
                    "L 10\n" +
                    "R 12\n" +
                    "D 3\n" +
                    "R 11\n" +
                    "U 11\n" +
                    "D 7\n" +
                    "L 10\n" +
                    "D 15\n" +
                    "U 13\n" +
                    "R 5\n" +
                    "D 8\n" +
                    "U 12\n" +
                    "L 3\n" +
                    "R 6\n" +
                    "D 10\n" +
                    "R 5\n" +
                    "U 8\n" +
                    "R 16\n" +
                    "U 16\n" +
                    "D 3\n" +
                    "R 11\n" +
                    "D 7\n" +
                    "U 4\n" +
                    "R 14\n" +
                    "L 12\n" +
                    "U 5\n" +
                    "L 1\n" +
                    "U 14\n" +
                    "L 15\n" +
                    "R 13\n" +
                    "U 16\n" +
                    "D 6\n" +
                    "U 7\n" +
                    "D 11\n" +
                    "L 11\n" +
                    "U 13\n" +
                    "R 10\n" +
                    "D 16\n" +
                    "U 14\n" +
                    "L 1\n" +
                    "D 17\n" +
                    "U 14\n" +
                    "D 2\n" +
                    "L 17\n" +
                    "U 1\n" +
                    "L 6\n" +
                    "D 17\n" +
                    "R 13\n" +
                    "L 10\n" +
                    "U 16\n" +
                    "L 3\n" +
                    "U 4\n" +
                    "D 4\n" +
                    "L 2\n" +
                    "D 10\n" +
                    "L 2\n" +
                    "R 11\n" +
                    "L 14\n" +
                    "D 6\n" +
                    "U 13\n" +
                    "R 8\n" +
                    "D 8\n" +
                    "L 4\n" +
                    "U 8\n" +
                    "D 17\n" +
                    "R 11\n" +
                    "L 7\n" +
                    "U 15\n" +
                    "L 7\n" +
                    "R 11\n" +
                    "D 13\n" +
                    "U 3\n" +
                    "R 12\n" +
                    "D 9\n" +
                    "L 11\n" +
                    "D 14\n" +
                    "U 10\n" +
                    "L 11\n" +
                    "D 13\n" +
                    "L 17\n" +
                    "R 7\n" +
                    "D 4\n" +
                    "R 16\n" +
                    "D 1\n" +
                    "U 8\n" +
                    "L 6\n" +
                    "R 9\n" +
                    "L 7\n" +
                    "D 2\n" +
                    "L 3\n" +
                    "D 13\n" +
                    "L 6\n" +
                    "U 8\n" +
                    "L 13\n" +
                    "U 6\n" +
                    "L 12\n" +
                    "U 5\n" +
                    "D 1\n" +
                    "R 10\n" +
                    "L 17\n" +
                    "D 13\n" +
                    "U 1\n" +
                    "L 9\n" +
                    "R 8\n" +
                    "D 10\n" +
                    "U 10\n" +
                    "R 6\n" +
                    "U 17\n" +
                    "R 16\n" +
                    "D 3\n" +
                    "L 4\n" +
                    "D 13\n" +
                    "L 1\n" +
                    "U 6\n" +
                    "R 15\n" +
                    "U 6\n" +
                    "D 6\n" +
                    "U 1\n" +
                    "D 12\n" +
                    "U 12\n" +
                    "R 6\n" +
                    "D 2\n" +
                    "R 13\n" +
                    "D 16\n" +
                    "L 14\n" +
                    "D 16\n" +
                    "U 12\n" +
                    "R 13\n" +
                    "U 14\n" +
                    "R 4\n" +
                    "U 3\n" +
                    "D 3\n" +
                    "R 11\n" +
                    "U 2\n" +
                    "L 17\n" +
                    "R 13\n" +
                    "D 2\n" +
                    "R 5\n" +
                    "L 5\n" +
                    "D 17\n" +
                    "R 9\n" +
                    "D 3\n" +
                    "U 16\n" +
                    "R 8\n" +
                    "L 18\n" +
                    "R 12\n" +
                    "L 8\n" +
                    "R 10\n" +
                    "L 9\n" +
                    "R 4\n" +
                    "U 1\n" +
                    "D 4\n" +
                    "U 7\n" +
                    "L 2\n" +
                    "D 9\n" +
                    "R 12\n" +
                    "D 2\n" +
                    "R 1\n" +
                    "U 11\n" +
                    "D 4\n" +
                    "L 16\n" +
                    "U 18\n" +
                    "D 3\n" +
                    "R 14\n" +
                    "L 4\n" +
                    "U 2\n" +
                    "L 16\n" +
                    "R 4\n" +
                    "L 5\n" +
                    "D 3\n" +
                    "U 17\n" +
                    "R 3\n" +
                    "U 5\n" +
                    "R 8\n" +
                    "D 4\n" +
                    "L 3\n" +
                    "D 18\n" +
                    "L 12\n" +
                    "D 17\n" +
                    "U 15\n" +
                    "L 1\n" +
                    "D 17\n" +
                    "R 11\n" +
                    "U 5\n" +
                    "R 3\n" +
                    "L 16\n" +
                    "R 6\n" +
                    "L 14\n" +
                    "R 4\n" +
                    "U 15\n" +
                    "D 7\n" +
                    "R 15\n" +
                    "L 17\n" +
                    "U 14\n" +
                    "L 9\n" +
                    "R 9\n" +
                    "L 9\n" +
                    "D 11\n" +
                    "L 10\n" +
                    "U 7\n" +
                    "L 1\n" +
                    "U 11\n" +
                    "R 4\n" +
                    "U 7\n" +
                    "L 10\n" +
                    "D 16\n" +
                    "R 3\n" +
                    "L 17\n" +
                    "R 16\n" +
                    "L 9\n" +
                    "D 4\n" +
                    "R 17\n" +
                    "L 7\n" +
                    "U 5\n" +
                    "D 16\n" +
                    "R 5\n" +
                    "D 13\n" +
                    "U 5\n" +
                    "R 8\n" +
                    "D 10\n" +
                    "R 1\n" +
                    "L 2\n" +
                    "R 10\n" +
                    "U 12\n" +
                    "D 2\n" +
                    "U 12\n" +
                    "L 10\n" +
                    "R 6\n" +
                    "L 18\n" +
                    "U 7\n" +
                    "D 9\n" +
                    "R 16\n" +
                    "L 18\n" +
                    "D 17\n" +
                    "R 14\n" +
                    "U 9\n" +
                    "R 5\n" +
                    "D 4\n" +
                    "R 18\n" +
                    "D 6\n" +
                    "R 7\n" +
                    "U 12\n" +
                    "L 7\n" +
                    "D 11\n" +
                    "U 12\n" +
                    "R 12\n" +
                    "U 4\n" +
                    "L 8\n" +
                    "U 6\n" +
                    "D 11\n" +
                    "L 8\n" +
                    "R 18\n" +
                    "U 12\n" +
                    "R 2\n" +
                    "U 13\n" +
                    "D 3\n" +
                    "R 10\n" +
                    "D 4\n" +
                    "R 10\n" +
                    "L 18\n" +
                    "D 1\n" +
                    "L 18\n" +
                    "U 2\n" +
                    "D 19\n" +
                    "U 14\n" +
                    "L 14\n" +
                    "U 3\n" +
                    "D 14\n" +
                    "R 4\n" +
                    "L 10\n" +
                    "D 13\n" +
                    "R 6\n" +
                    "D 14\n" +
                    "R 13\n" +
                    "D 13\n" +
                    "R 11\n" +
                    "U 16\n" +
                    "L 18\n" +
                    "U 3\n" +
                    "R 8\n" +
                    "U 17\n" +
                    "R 7\n" +
                    "L 12\n" +
                    "D 3\n" +
                    "L 6\n" +
                    "R 6\n" +
                    "D 18\n" +
                    "L 2\n" +
                    "D 16\n" +
                    "R 1\n" +
                    "U 16\n" +
                    "R 14\n" +
                    "L 9\n" +
                    "D 6\n" +
                    "L 5\n" +
                    "D 6\n" +
                    "U 9\n" +
                    "L 11\n" +
                    "D 18\n" +
                    "R 5\n" +
                    "L 15\n" +
                    "D 18\n" +
                    "R 18\n" +
                    "L 3\n" +
                    "R 18\n" +
                    "L 18\n" +
                    "R 2\n" +
                    "L 15\n" +
                    "R 12\n" +
                    "D 9\n" +
                    "L 3\n" +
                    "U 17\n" +
                    "R 1\n" +
                    "U 18\n" +
                    "D 16\n" +
                    "U 17\n" +
                    "L 5\n" +
                    "U 9\n" +
                    "R 4\n" +
                    "L 14\n" +
                    "D 15\n" +
                    "R 11\n" +
                    "U 18\n" +
                    "L 19\n" +
                    "U 12\n" +
                    "R 13\n" +
                    "U 16\n" +
                    "D 16\n" +
                    "L 8\n" +
                    "D 16\n" +
                    "R 4\n" +
                    "U 5\n" +
                    "D 18\n" +
                    "R 13\n" +
                    "D 13\n" +
                    "U 9\n" +
                    "R 14\n" +
                    "L 14\n" +
                    "U 17\n" +
                    "D 9\n" +
                    "L 8\n" +
                    "R 18\n" +
                    "L 12\n" +
                    "R 16\n" +
                    "L 11\n" +
                    "U 14\n" +
                    "D 2\n" +
                    "L 19\n" +
                    "U 19\n" +
                    "D 11\n" +
                    "R 11\n" +
                    "U 16\n" +
                    "D 15\n" +
                    "U 16\n" +
                    "L 18\n" +
                    "D 3\n" +
                    "L 18\n" +
                    "U 7\n" +
                    "L 14\n" +
                    "D 6\n" +
                    "U 9\n" +
                    "D 2\n" +
                    "L 19\n" +
                    "D 17";

}
